sudo: false
language: c
matrix:
  include:
    - os: linux
      language: python
      python: "3.4"
      env: MODE=lint
    - os: linux
      env: MODE=deploy
    - os: linux
      env: MODE=deploy-bleed
    - os: osx
      env: MODE=deploy
    - os: osx
      env: MODE=deploy-bleed
  # osx builds are often very slow to start due to high demand
  fast_finish: true
  allow_failures:
    - os: osx
script: |
  case $MODE in
    lint)
      pip install -r requirements.txt
      ./bin/repos-lint ./etc/repos.yaml
      ;;
    deploy*)
      if [[ $MODE == deploy-bleed ]]; then
        echo -e "*** testing with BLEED conda/pip packages ***\n"
        ./bin/deploy -b
      else
        echo -e "*** testing with PINNED conda/pip packages ***\n"
        ./bin/deploy
      fi
      . ./bin/setup.sh
      echo -e "*** checking installed vs conda_packages.txt conda packages ***\n"
      conda list -e > ./etc/conda_packages.txt
      git diff
      rebuild cfitsio
      ;;
    *)
      echo "unknown MODE: $MODE"
      exit 1
      ;;
  esac
notifications:
  email: false
  hipchat:
    rooms:
      secure: hiu+I6yS6iQBguNNyuJ2H6HCUi2575zGgA74vuGIIViFPPF2Oc1Ty18u4ahygglaOzXh9FgFP0XEYhKE1FYPmeneP0bI/u9sr4ruEOUnC1xUyv1ClmsakzNZucQ2N7oeEEY0FOZK2VpQw44cisVdtVQFnTqf99Hj2fGP1+2LIWo=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
